name: sasa_play
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'
dependencies: 
  animated_text_kit: ^4.2.2
  appinio_video_player: ^1.2.0
  camera: ^0.10.0+4
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.1.1
  flick_video_player: ^0.5.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  loading_animation_widget: ^1.2.0+3
  like_button: ^2.0.5
  photo_view: ^0.14.0
  progress_loader_overlay: ^3.0.2
  provider: ^6.0.4
  stacked: ^3.0.1
  video_player: ^2.4.8
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  pubspec_dependency_sorter: ^0.0.2
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets:
    - 'assets/images/'
