name: sasa_play
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'
dependencies: 
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  camera: ^0.10.0+4
  flex_color_scheme: ^6.1.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  provider: ^6.0.4
  flutter_svg: ^1.1.6
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.1
  get_storage: ^2.0.3
  animated_text_kit: ^4.2.2
  progress_loader_overlay: ^3.0.2
  loading_animation_widget: ^1.2.0+3
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  pubspec_dependency_sorter: ^0.0.2
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
